[theme]
primaryColor = "#7C3AED"               # purple
backgroundColor = "#070A12"
secondaryBackgroundColor = "#0C1222"
textColor = "#E9EDFA"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableXsrfProtection = true
